#pragma once



enum RENDER_PRIORITY{
    RENDER_PRIORITY_SETUP = 0,
    RENDER_PRIORITY_FIRST = 100,
    RENDER_PRIORITY_CAMERA = 200,
    RENDER_PRIORITY_STANDARD = 300,
    RENDER_PRIORITY_LAST = 400,
    RENDER_PRIORITY_UNSETUP = 500
};